gb_bile_mo:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /
    
api_login_check:
    path: /login_check

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   api/doc

