gb_bile_mo:
    resource: "@GBBileMoBundle/Controller/"
    type:     annotation
    prefix:   /
    
api_login_check:
    path: /login_check

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing/swaggerui.xml"
    prefix:   /doc

