security:

    encoders:
        AppBundle\Entity\Store: 
            algorithm: bcrypt
    
    providers:
        store:
            entity:
                class: AppBundle\Entity\Store
                property: userName
            
    firewalls:
        api_doc:
            pattern: ^/api/doc
            security: false
        login:
            pattern:  ^/login
            stateless: true
            anonymous: true
            form_login:
                check_path:               /login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false      
        main:
            pattern:   ^/
            provider: store
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/,       roles: ROLE_USER }