# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    encoders:
        GB\BileMoBundle\Entity\Store: 
            algorithm: sha512
            encode_as_base64: false
            iterations: 1
    
    providers:
        store:
            entity:
                class: GB\BileMoBundle\Entity\Store
                property: userName
            
    firewalls:
        login:
            pattern:  ^/login
            stateless: true
            anonymous: true
            form_login:
                check_path:               /login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false
        api_doc:
            pattern: ^api/doc
            security: false        
        main:
            pattern:   ^/(customers|phones)
            provider: store
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/,       roles: IS_AUTHENTICATED_FULLY }