services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
    
    GB\BileMoBundle\Controller\BileMoController:
        tags: 
            - 'controller.service_arguments'
            - 'fos_rest.exception.twig_controller'

    